// Editor
export const EDITOR_TEXT = "EDITOR_TEXT";
export const EDITOR_WITHOUT_TEXT = "EDITOR_WITHOUT_TEXT";

// Fab
export const FAB_EDITOR_TEXT = "FAB_EDITOR_TEXT";
export const FAB_EDITOR_WITHOUT_TEXT = "FAB_EDITOR_WITHOUT_TEXT";

// Placeholder
export const PLACE_HOLDER_SHOW = "PLACE_HOLDER_SHOW";
